from: markdown

to: pdf

output-file: rapport-eco.pdf

input-files:
  - ./rapport-eco.md

template: eisvogel

metadata:
  mainfont: calibri
  fontsize: 12pt
  language: fr-FR
  type: report
  colorlinks: true
  title: "Mémoire d'Économie des Logiciels Libres"
  author: Maxime Oçafrain
  date: "15-12-2019"
  subject: "Mémoire"
  keywords: [Markdown, Mémoire]
  subtitle: "Étude de cas des modèles économiques des logiciels libres"

table-of-contents: true

highlight-style: zenburn

variables:
  documentclass: article
  toc-own-page: true
  logo: ./img/imageedit_2_6639094819.png
  logo-width: 250
  titlepage: true,
  titlepage-rule-color: "3DC4D4"
  titlepage-background: "./img/canvas.png"
